## Homework 4 Table of contentï¼š<a class="anchor" id="bullet8"></a>
* [1. ](#bullet1)
* [2. ](#bullet2)
* [3. ](#bullet3)
* [4. ](#bullet4)
* [5. ](#bullet5)
* [6. ](#bullet6)
* [7. ](#bullet7)

In [1]:
#import library
import pandas as pd
import numpy as np
import statsmodels.api as sm

#### 1. [15 pts] Import the data as a pd.DataFrame object. Use one or more functions from the pandas library to split the data into three unique datasets. The first should include columns that are factors only (i.e. - categorical data), the second should include columns that are numeric only, and the third should include columns with logical values only.<a class="anchor" id="bullet1"></a>

In [2]:
#data import
hp = pd.read_csv("Housing_prices_data.csv")
print(hp.dtypes)
hp.dtypes.unique()

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

array([dtype('int64'), dtype('O'), dtype('float64'), dtype('bool')],
      dtype=object)

In [3]:
# select categorical columns
"""
cat_data = hp.select_dtypes(include=['object'])

# select numeric columns
num_data = hp.select_dtypes(include=['int64', 'float64'])

# select logical columns
#A logical value is a single character (1 or 0) that is enclosed in single quotation marks
log_data = hp.select_dtypes(include=['bool'])
"""
def split_df_by_type(df):
    # Find columns with categorical data
    cat_cols = list(df.select_dtypes(include=['category', 'object']).columns)
    
    # Find columns with numeric data
    num_cols = list(df.select_dtypes(include=['int', 'float']).columns)
    
    # Find columns with boolean data
    bool_cols = list(df.select_dtypes(include=['bool']).columns)
    
    # Create new dataframes with only categorical, numeric, and boolean columns
    cat_df = df[cat_cols]
    num_df = df[num_cols]
    bool_df = df[bool_cols]
    
    return cat_df, num_df, bool_df

cat_df, num_df, bool_df = split_df_by_type(hp)
print(str(cat_df.dtypes.value_counts()) + "\n")
cat_df

object    42
dtype: int64

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1456,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
1457,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,...,Attchd,RFn,TA,TA,Y,NaN,GdPrv,Shed,WD,Normal
1458,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1459,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [4]:
print(str(num_df.dtypes.value_counts()) + "\n")
num_df

int64      35
float64     3
dtype: int64

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,736,68,0,0,0,0,0,6,2008,147500

In [5]:
print(str(bool_df.dtypes.value_counts()))
bool_df

bool    1
dtype: int64

      CentralAir
0           True
1           True
2           True
3           True
4           True
...          ...
1455        True
1456        True
1457        True
1458        True
1459        True

[1460 rows x 1 columns]

Hint: There is code we used in the HW last week that can be leveraged to split the dataset based on data types. There is also code in the /General Course Materials/Useful python functions.py file that can do this.

Remember that data frames can be thought of as a collection of lists/arrays/pd.Series objects saved in different columns. So think of each column in your data-frame as a pd.Series and split based on column type. Note that pandas has a dtype called "object", which it uses when it cannot determine the datatype. Generally, pandas will save string variables as object data types. For this question, treat the object as a categorical factor.

#### 2. [15 pts] <a class="anchor" id="bullet2"></a>Using the second dataset from question #1, for each numeric variable use the apply function to return the mean, median and standard deviation (SD) of all numeric variables.

In [6]:
#return the mean, median and standard deviation for num_df:
def sum_stats(col):
    return pd.Series({"Mean": col.mean(),
                      "Median": col.median(),
                      "Std": col.std()})

stat_of_num = num_df.apply(sum_stats)
stat_of_num

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
Mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
Median,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
Std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883

#### 3. [15 pts]Using the second dataset from question <a class="anchor" id="bullet3"></a>#1, create a new dataset that only includes the variable indicating sales price ("SalePrice"). Search for a categorical variable which has between 2-4 categories in the full dataset that you think may be related to the sales price of houses. Give the mean, median and SD for SalePrice based on the different groups of the categorical variables. Does the average price seem to vary by the different levels of the categorical factor you chose?

In [7]:
#create a dataset only includes SalePrice:
sale_price = num_df[["SalePrice"]]
sale_price

      SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [8]:
#check which category variable I am picking:
 #check the unique to see how many categories in each variable:
for col in cat_df:
    print(col + " " + str(len(cat_df[col].unique())))

MSZoning 5
Street 2
Alley 3
LotShape 4
LandContour 4
Utilities 2
LotConfig 5
LandSlope 3
Neighborhood 25
Condition1 9
Condition2 8
BldgType 5
HouseStyle 8
RoofStyle 6
RoofMatl 8
Exterior1st 15
Exterior2nd 16
MasVnrType 5
ExterQual 4
ExterCond 5
Foundation 6
BsmtQual 5
BsmtCond 5
BsmtExposure 5
BsmtFinType1 7
BsmtFinType2 7
Heating 6
HeatingQC 5
Electrical 6
KitchenQual 4
Functional 7
FireplaceQu 6
GarageType 7
GarageFinish 4
GarageQual 6
GarageCond 6
PavedDrive 3
PoolQC 4
Fence 5
MiscFeature 5
SaleType 9
SaleCondition 6

In [10]:
#data explanation:
#LandSlope: Slope of property
#
#Gtl: Gentle slope
#Mod: Moderate Slope	
#Sev: Severe Slope
#dropna incase there is fifth category:
hp1 = hp.dropna(subset = ["LandSlope"])
#mean, median and SD for SalePrice based on the different groups of the Fence
stats_hp_to_fence = hp1.groupby('LandSlope')['SalePrice'].agg(['mean', 'median', 'std'])
#round to 2 decimals:
stats_hp_to_fence.round(2)

                mean    median       std
LandSlope
Gtl        179956.80  161875.0  78669.37
Mod        196734.14  186700.0  92375.36
Sev        204379.23  185000.0  86729.92

So the mean and median of SalePrice actually dropped from Good Privacy Fence to Mimimum Privacy Fence AND from Good Wood Fance to Minimum Wood/Wire Fance.

#### 4. [15 pts] <a class="anchor" id="bullet4"></a>First, regress "SalePrice" on "LotArea", "OverallQual", "OverallCond" with the statsmodels library. Use the syntax below to replicate the output shown.

In [11]:
#build x and y
x = hp [["LotArea", "OverallQual", "OverallCond"]]
y = (hp["SalePrice"])
x = sm.add_constant(x)

C:\Apps\anaconda\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

In [12]:
#fit linear regression model:
model_OLS = sm.OLS(y,x).fit()

#view model summary
print(model_OLS.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.659
Model:                            OLS   Adj. R-squared:                  0.658
Method:                 Least Squares   F-statistic:                     935.9
Date:                Wed, 01 Mar 2023   Prob (F-statistic):               0.00
Time:                        17:17:16   Log-Likelihood:                -17760.
No. Observations:                1460   AIC:                         3.553e+04
Df Residuals:                    1456   BIC:                         3.555e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const       -1.022e+05   8633.073    -11.832      0.000   -1.19e+05   -8.52e+04
LotArea         1.4503      0.123     11.831      0.000       1.210       1.691
OverallQual   4.43e+04    888.434     49.860      0.000    4.26e+04     4.6e+04
OverallCond  -423.6737   1097.973     -0.386      0.700   -2577.451    1730.104
==============================================================================
Omnibus:                      574.483   Durbin-Watson:                   1.966
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7330.883
Skew:                           1.468   Prob(JB):                         0.00
Kurtosis:                      13.578   Cond. No.                     1.04e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.04e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

#### Second, write a for loop that loops through each level of the categorical factor you chose in Q3, where each iteration of the for loop subsets your data for one group of the categorical variable at a time, and then fits the same regression model specified above k times, where k refers to the number of unique categories. On each iteration of your for loop, store the model.summary() information as a new element in a list object. Once your for loop is done running, print the list. There should be k regressions which you estimated.

In [13]:
#dropna incase there is fifth category:
hp1 = hp.dropna(subset = ["LandSlope"])

#still the same x,y: 
X = hp1[["LotArea", "OverallQual", "OverallCond"]]
y = (hp1["SalePrice"])
X = sm.add_constant(X)

# subset the data for the current category
#data = hp1[hp1['LandSlope'] == category]

# create a list to store regression result
results = []

#Select my own Category Variable
cat_select = "LandSlope"

# loop through each category of Fence, for total of 4 times:
for cat_var in hp1[cat_select].unique():
    #create my regression y,x:
    X1 = X[hp1[cat_select] == cat_var]
    y1 = y[hp1[cat_select] == cat_var]
    
    # use previous builded regression model to generate the results list
    model = sm.OLS(y1,X1).fit()
    #fit linear regression model:
    results.append(model.summary())

#utilize enumerate to print the result:
for i, summary in enumerate(results):
    print(f"-----Summary for category {hp1['LandSlope'].unique()[i]}-----\n{summary}\n\nNext Category:\n")

-----Summary for category Gtl-----
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.679
Model:                            OLS   Adj. R-squared:                  0.678
Method:                 Least Squares   F-statistic:                     971.5
Date:                Wed, 01 Mar 2023   Prob (F-statistic):               0.00
Time:                        17:17:18   Log-Likelihood:                -16755.
No. Observations:                1382   AIC:                         3.352e+04
Df Residuals:                    1378   BIC:                         3.354e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const       -1.152e+05   8823.055    -13.062      0.000   -1.33e+05   -9.79e+04
LotArea         3.5245      0.266     13.226      0.000       3.002       4.047
OverallQual    4.3e+04    909.427     47.279      0.000    4.12e+04    4.48e+04
OverallCond  -432.8916   1098.587     -0.394      0.694   -2587.976    1722.193
==============================================================================
Omnibus:                      501.939   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            12469.483
Skew:                           1.116   Prob(JB):                         0.00
Kurtosis:                      17.545   Cond. No.                     8.01e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.01e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Next Category:

-----Summary for category Mod-----
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.699
Model:                            OLS   Adj. R-squared:                  0.684
Method:                 Least Squares   F-statistic:                     47.27
Date:                Wed, 01 Mar 2023   Prob (F-statistic):           6.49e-16
Time:                        17:17:18   Log-Likelihood:                -795.87
No. Observations:                  65   AIC:                             1600.
Df Residuals:                      61   BIC:                             1608.
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const        -1.14e+05   3.62e+04     -3.152      0.003   -1.86e+05   -4.17e+04
LotArea         2.3235      0.501      4.633      0.000       1.321       3.326
OverallQual  4.304e+04   4398.423      9.784      0.000    3.42e+04    5.18e+04
OverallCond  4810.5746   5642.333      0.853      0.397   -6471.967    1.61e+04
==============================================================================
Omnibus:                        4.717   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.095   Jarque-Bera (JB):                4.476
Skew:                           0.335   Prob(JB):                        0.107
Kurtosis:                       4.097   Cond. No.                     1.12e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.12e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

Next Category:

-----Summary for category Sev-----
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.931
Method:                 Least Squares   F-statistic:                     54.76
Date:                Wed, 01 Mar 2023   Prob (F-statistic):           4.20e-06
Time:                        17:17:18   Log-Likelihood:                -146.52
No. Observations:                  13   AIC:                             301.0
Df Residuals:                       9   BIC:                             303.3
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const        6757.7517    2.5e+04      0.271      0.793   -4.97e+04    6.33e+04
LotArea         0.6628      0.101      6.543      0.000       0.434       0.892
OverallQual  4.031e+04   5853.533      6.886      0.000    2.71e+04    5.36e+04
OverallCond  -1.23e+04   5313.790     -2.316      0.046   -2.43e+04    -283.778
==============================================================================
Omnibus:                        3.346   Durbin-Watson:                   1.747
Prob(Omnibus):                  0.188   Jarque-Bera (JB):                1.158
Skew:                          -0.157   Prob(JB):                        0.561
Kurtosis:                       1.572   Cond. No.                     3.81e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.81e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

Next Category:

C:\Apps\anaconda\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)
C:\Apps\anaconda\lib\site-packages\scipy\stats\stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=13
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

#### Does the effect of LotArea on SalePrice vary within the different levels of the categorical factor you chose? What is another, more common way to answer a question like this (i.e., a question about moderation or effect heterogeneity)? Hint: Compare the slope estimates and also account for the standard error.

#Gtl: Gentle slope
#Mod: Moderate Slope	
#Sev: Severe Slope
    So the effect of the LotArea have a significant drop from Gentle slop to Severe slop for all three variables:  
LotArea dropped from 3.5245 to 2.3235 then to 0.6628; while it remains statistically significant.  
  
And we could summrize that SalePrice is vary between different levels of categories in my categorical variable, and this represent that 1 unit increase for the gentle slope will have a 3.5245 unit increase in sale price, which is the largest effect in all categories.  

As we can see from the Standard Error under this sample size,all three categories are statistically significant, and the S.E. are all very small, (0.1, 0.5, and 0.2)
  
For the problem of herogeneity, we could use different T-test or anova to solve the problem if there is an heterogeneity, or we could use an interaction term to solve herogeneity.

#### 5. [15 pts] Using the first dataset from question <a class="anchor" id="bullet5"></a>#1, for each categorical variable use a for loop to print a frequency and relative frequency for every variable. To make your output readable, for each variable you should print the following in this order, placing the variable name where you see blanks below.

In [14]:
#create a for loop to count each for each categorical variable:
for col in cat_df: #because it want us use the dataset from Q1
    #build frequency table
    frq_table = cat_df[col].value_counts()
    #"Frequency table for ______ ============"
    print(f"Frequency table for {col} ============")
    #Display the frequency table
    print(frq_table)

    # Skip a line, and print "Relative frequency table for ______ ============"
    print(f"\nRelative frequency table for {col} ============") 
    #this f let me write a Python expression between { } characters that can refer to variables Inside this string
    print(frq_table / frq_table.sum())

    # Skip two lines before printing the data for the next categorical variable
    print("\n\n")

Frequency table for MSZoning ============
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64

Relative frequency table for MSZoning ============
RL         0.788356
RM         0.149315
FV         0.044521
RH         0.010959
C (all)    0.006849
Name: MSZoning, dtype: float64



Frequency table for Street ============
Pave    1454
Grvl       6
Name: Street, dtype: int64

Relative frequency table for Street ============
Pave    0.99589
Grvl    0.00411
Name: Street, dtype: float64



Frequency table for Alley ============
Grvl    50
Pave    41
Name: Alley, dtype: int64

Relative frequency table for Alley ============
Grvl    0.549451
Pave    0.450549
Name: Alley, dtype: float64



Frequency table for LotShape ============
Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64

Relative frequency table for LotShape ============
Reg    0.633562
IR1    0.331507
IR2    0.028082
IR3    0.006849
Name: LotShape, dtype: float64



Frequency table for LandContour ============
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: LandContour, dtype: int64

Relative frequency table for LandContour ============
Lvl    0.897945
Bnk    0.043151
HLS    0.034247
Low    0.024658
Name: LandContour, dtype: float64



Frequency table for Utilities ============
AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64

Relative frequency table for Utilities ============
AllPub    0.999315
NoSeWa    0.000685
Name: Utilities, dtype: float64



Frequency table for LotConfig ============
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: LotConfig, dtype: int64

Relative frequency table for LotConfig ============
Inside     0.720548
Corner     0.180137
CulDSac    0.064384
FR2        0.032192
FR3        0.002740
Name: LotConfig, dtype: float64



Frequency table for LandSlope ============
Gtl    1382
Mod      65
Sev      13
Name: LandSlope, dtype: int64

Relative frequency table for LandSlope ============
Gtl    0.946575
Mod    0.044521
Sev    0.008904
Name: LandSlope, dtype: float64



Frequency table for Neighborhood ============
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64

Relative frequency table for Neighborhood ============
NAmes      0.154110
CollgCr    0.102740
OldTown    0.077397
Edwards    0.068493
Somerst    0.058904
Gilbert    0.054110
NridgHt    0.052740
Sawyer     0.050685
NWAmes     0.050000
SawyerW    0.040411
BrkSide    0.039726
Crawfor    0.034932
Mitchel    0.033562
NoRidge    0.028082
Timber     0.026027
IDOTRR     0.025342
ClearCr    0.019178
StoneBr    0.017123
SWISU      0.017123
MeadowV    0.011644
Blmngtn    0.011644
BrDale     0.010959
Veenker    0.007534
NPkVill    0.006164
Blueste    0.001370
Name: Neighborhood, dtype: float64



Frequency table for Condition1 ============
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: Condition1, dtype: int64

Relative frequency table for Condition1 ============
Norm      0.863014
Feedr     0.055479
Artery    0.032877
RRAn      0.017808
PosN      0.013014
RRAe      0.007534
PosA      0.005479
RRNn      0.003425
RRNe      0.001370
Name: Condition1, dtype: float64



Frequency table for Condition2 ============
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: Condition2, dtype: int64

Relative frequency table for Condition2 ============
Norm      0.989726
Feedr     0.004110
Artery    0.001370
RRNn      0.001370
PosN      0.001370
PosA      0.000685
RRAn      0.000685
RRAe      0.000685
Name: Condition2, dtype: float64



Frequency table for BldgType ============
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: BldgType, dtype: int64

Relative frequency table for BldgType ============
1Fam      0.835616
TwnhsE    0.078082
Duplex    0.035616
Twnhs     0.029452
2fmCon    0.021233
Name: BldgType, dtype: float64



Frequency table for HouseStyle ============
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64

Relative frequency table for HouseStyle ============
1Story    0.497260
2Story    0.304795
1.5Fin    0.105479
SLvl      0.044521
SFoyer    0.025342
1.5Unf    0.009589
2.5Unf    0.007534
2.5Fin    0.005479
Name: HouseStyle, dtype: float64



Frequency table for RoofStyle ============
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: RoofStyle, dtype: int64

Relative frequency table for RoofStyle ============
Gable      0.781507
Hip        0.195890
Flat       0.008904
Gambrel    0.007534
Mansard    0.004795
Shed       0.001370
Name: RoofStyle, dtype: float64



Frequency table for RoofMatl ============
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: RoofMatl, dtype: int64

Relative frequency table for RoofMatl ============
CompShg    0.982192
Tar&Grv    0.007534
WdShngl    0.004110
WdShake    0.003425
Metal      0.000685
Membran    0.000685
Roll       0.000685
ClyTile    0.000685
Name: RoofMatl, dtype: float64



Frequency table for Exterior1st ============
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: Exterior1st, dtype: int64

Relative frequency table for Exterior1st ============
VinylSd    0.352740
HdBoard    0.152055
MetalSd    0.150685
Wd Sdng    0.141096
Plywood    0.073973
CemntBd    0.041781
BrkFace    0.034247
WdShing    0.017808
Stucco     0.017123
AsbShng    0.013699
BrkComm    0.001370
Stone      0.001370
AsphShn    0.000685
ImStucc    0.000685
CBlock     0.000685
Name: Exterior1st, dtype: float64



Frequency table for Exterior2nd ============
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: Exterior2nd, dtype: int64

Relative frequency table for Exterior2nd ============
VinylSd    0.345205
MetalSd    0.146575
HdBoard    0.141781
Wd Sdng    0.134932
Plywood    0.097260
CmentBd    0.041096
Wd Shng    0.026027
Stucco     0.017808
BrkFace    0.017123
AsbShng    0.013699
ImStucc    0.006849
Brk Cmn    0.004795
Stone      0.003425
AsphShn    0.002055
Other      0.000685
CBlock     0.000685
Name: Exterior2nd, dtype: float64



Frequency table for MasVnrType ============
None       864
BrkFace    445
Stone      128
BrkCmn      15
Name: MasVnrType, dtype: int64

Relative frequency table for MasVnrType ============
None       0.595041
BrkFace    0.306474
Stone      0.088154
BrkCmn     0.010331
Name: MasVnrType, dtype: float64



Frequency table for ExterQual ============
TA    906
Gd    488
Ex     52
Fa     14
Name: ExterQual, dtype: int64

Relative frequency table for ExterQual ============
TA    0.620548
Gd    0.334247
Ex    0.035616
Fa    0.009589
Name: ExterQual, dtype: float64



Frequency table for ExterCond ============
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: ExterCond, dtype: int64

Relative frequency table for ExterCond ============
TA    0.878082
Gd    0.100000
Fa    0.019178
Ex    0.002055
Po    0.000685
Name: ExterCond, dtype: float64



Frequency table for Foundation ============
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: Foundation, dtype: int64

Relative frequency table for Foundation ============
PConc     0.443151
CBlock    0.434247
BrkTil    0.100000
Slab      0.016438
Stone     0.004110
Wood      0.002055
Name: Foundation, dtype: float64



Frequency table for BsmtQual ============
TA    649
Gd    618
Ex    121
Fa     35
Name: BsmtQual, dtype: int64

Relative frequency table for BsmtQual ============
TA    0.456079
Gd    0.434294
Ex    0.085032
Fa    0.024596
Name: BsmtQual, dtype: float64



Frequency table for BsmtCond ============
TA    1311
Gd      65
Fa      45
Po       2
Name: BsmtCond, dtype: int64

Relative frequency table for BsmtCond ============
TA    0.921293
Gd    0.045678
Fa    0.031623
Po    0.001405
Name: BsmtCond, dtype: float64



Frequency table for BsmtExposure ============
No    953
Av    221
Gd    134
Mn    114
Name: BsmtExposure, dtype: int64

Relative frequency table for BsmtExposure ============
No    0.670183
Av    0.155415
Gd    0.094233
Mn    0.080169
Name: BsmtExposure, dtype: float64



Frequency table for BsmtFinType1 ============
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: BsmtFinType1, dtype: int64

Relative frequency table for BsmtFinType1 ============
Unf    0.302178
GLQ    0.293746
ALQ    0.154603
BLQ    0.104006
Rec    0.093465
LwQ    0.052003
Name: BsmtFinType1, dtype: float64



Frequency table for BsmtFinType2 ============
Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: BsmtFinType2, dtype: int64

Relative frequency table for BsmtFinType2 ============
Unf    0.883263
Rec    0.037975
LwQ    0.032349
BLQ    0.023207
ALQ    0.013361
GLQ    0.009845
Name: BsmtFinType2, dtype: float64



Frequency table for Heating ============
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: Heating, dtype: int64

Relative frequency table for Heating ============
GasA     0.978082
GasW     0.012329
Grav     0.004795
Wall     0.002740
OthW     0.001370
Floor    0.000685
Name: Heating, dtype: float64



Frequency table for HeatingQC ============
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: HeatingQC, dtype: int64

Relative frequency table for HeatingQC ============
Ex    0.507534
TA    0.293151
Gd    0.165068
Fa    0.033562
Po    0.000685
Name: HeatingQC, dtype: float64



Frequency table for Electrical ============
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

Relative frequency table for Electrical ============
SBrkr    0.914325
FuseA    0.064428
FuseF    0.018506
FuseP    0.002056
Mix      0.000685
Name: Electrical, dtype: float64



Frequency table for KitchenQual ============
TA    735
Gd    586
Ex    100
Fa     39
Name: KitchenQual, dtype: int64

Relative frequency table for KitchenQual ============
TA    0.503425
Gd    0.401370
Ex    0.068493
Fa    0.026712
Name: KitchenQual, dtype: float64



Frequency table for Functional ============
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: Functional, dtype: int64

Relative frequency table for Functional ============
Typ     0.931507
Min2    0.023288
Min1    0.021233
Mod     0.010274
Maj1    0.009589
Maj2    0.003425
Sev     0.000685
Name: Functional, dtype: float64



Frequency table for FireplaceQu ============
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: FireplaceQu, dtype: int64

Relative frequency table for FireplaceQu ============
Gd    0.493506
TA    0.406494
Fa    0.042857
Ex    0.031169
Po    0.025974
Name: FireplaceQu, dtype: float64



Frequency table for GarageType ============
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64

Relative frequency table for GarageType ============
Attchd     0.630892
Detchd     0.280638
BuiltIn    0.063814
Basment    0.013778
CarPort    0.006526
2Types     0.004351
Name: GarageType, dtype: float64



Frequency table for GarageFinish ============
Unf    605
RFn    422
Fin    352
Name: GarageFinish, dtype: int64

Relative frequency table for GarageFinish ============
Unf    0.438724
RFn    0.306019
Fin    0.255257
Name: GarageFinish, dtype: float64



Frequency table for GarageQual ============
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: GarageQual, dtype: int64

Relative frequency table for GarageQual ============
TA    0.950689
Fa    0.034808
Gd    0.010152
Ex    0.002175
Po    0.002175
Name: GarageQual, dtype: float64



Frequency table for GarageCond ============
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: GarageCond, dtype: int64

Relative frequency table for GarageCond ============
TA    0.961566
Fa    0.025381
Gd    0.006526
Po    0.005076
Ex    0.001450
Name: GarageCond, dtype: float64



Frequency table for PavedDrive ============
Y    1340
N      90
P      30
Name: PavedDrive, dtype: int64

Relative frequency table for PavedDrive ============
Y    0.917808
N    0.061644
P    0.020548
Name: PavedDrive, dtype: float64



Frequency table for PoolQC ============
Gd    3
Ex    2
Fa    2
Name: PoolQC, dtype: int64

Relative frequency table for PoolQC ============
Gd    0.428571
Ex    0.285714
Fa    0.285714
Name: PoolQC, dtype: float64



Frequency table for Fence ============
MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: Fence, dtype: int64

Relative frequency table for Fence ============
MnPrv    0.558719
GdPrv    0.209964
GdWo     0.192171
MnWw     0.039146
Name: Fence, dtype: float64



Frequency table for MiscFeature ============
Shed    49
Gar2     2
Othr     2
TenC     1
Name: MiscFeature, dtype: int64

Relative frequency table for MiscFeature ============
Shed    0.907407
Gar2    0.037037
Othr    0.037037
TenC    0.018519
Name: MiscFeature, dtype: float64



Frequency table for SaleType ============
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: SaleType, dtype: int64

Relative frequency table for SaleType ============
WD       0.867808
New      0.083562
COD      0.029452
ConLD    0.006164
ConLI    0.003425
ConLw    0.003425
CWD      0.002740
Oth      0.002055
Con      0.001370
Name: SaleType, dtype: float64



Frequency table for SaleCondition ============
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: SaleCondition, dtype: int64

Relative frequency table for SaleCondition ============
Normal     0.820548
Partial    0.085616
Abnorml    0.069178
Family     0.013699
Alloca     0.008219
AdjLand    0.002740
Name: SaleCondition, dtype: float64

"Frequency table for ______ ============"

Display the frequency table

Skip a line, and print "Relative frequency table for ______ ============"

Skip two lines before printing the data for the next categorical variable

This is what your output should look like for the MSZoning variable.

For example, for the MSZonig variable your output should look like this:
**CHECK PICTURE**

#### 6. [10 pts] Do the same thing as number 5, but with a while loop this time.<a class="anchor" id="bullet6"></a>

In [15]:
#while loop:
# initialize the loop variable
i = 0
#create columns:
cat_col = list(cat_df.columns)

# loop through each category variable:
while i < len(cat_col):
    col = cat_col[i]
    
    # create a frequency table
    freq_table = cat_df[col].value_counts()

    #"Frequency table for ______ ============"
    print(f"Frequency table for {col} ============")
    #Display the frequency table
    print(freq_table)

    #Skip a line, and print "Relative frequency table for ______ ============"
    print(f"\nRelative frequency table for {col} ============")
    print(freq_table / freq_table.sum())

    #Skip two lines before printing the data for the next categorical variable
    print("\n\n")
    
    #increment the loop variable
    i += 1

Frequency table for MSZoning ============
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64

Relative frequency table for MSZoning ============
RL         0.788356
RM         0.149315
FV         0.044521
RH         0.010959
C (all)    0.006849
Name: MSZoning, dtype: float64



Frequency table for Street ============
Pave    1454
Grvl       6
Name: Street, dtype: int64

Relative frequency table for Street ============
Pave    0.99589
Grvl    0.00411
Name: Street, dtype: float64



Frequency table for Alley ============
Grvl    50
Pave    41
Name: Alley, dtype: int64

Relative frequency table for Alley ============
Grvl    0.549451
Pave    0.450549
Name: Alley, dtype: float64



Frequency table for LotShape ============
Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64

Relative frequency table for LotShape ============
Reg    0.633562
IR1    0.331507
IR2    0.028082
IR3    0.006849
Name: LotShape, dtype: float64



Frequency table for LandContour ============
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: LandContour, dtype: int64

Relative frequency table for LandContour ============
Lvl    0.897945
Bnk    0.043151
HLS    0.034247
Low    0.024658
Name: LandContour, dtype: float64



Frequency table for Utilities ============
AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64

Relative frequency table for Utilities ============
AllPub    0.999315
NoSeWa    0.000685
Name: Utilities, dtype: float64



Frequency table for LotConfig ============
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: LotConfig, dtype: int64

Relative frequency table for LotConfig ============
Inside     0.720548
Corner     0.180137
CulDSac    0.064384
FR2        0.032192
FR3        0.002740
Name: LotConfig, dtype: float64



Frequency table for LandSlope ============
Gtl    1382
Mod      65
Sev      13
Name: LandSlope, dtype: int64

Relative frequency table for LandSlope ============
Gtl    0.946575
Mod    0.044521
Sev    0.008904
Name: LandSlope, dtype: float64



Frequency table for Neighborhood ============
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64

Relative frequency table for Neighborhood ============
NAmes      0.154110
CollgCr    0.102740
OldTown    0.077397
Edwards    0.068493
Somerst    0.058904
Gilbert    0.054110
NridgHt    0.052740
Sawyer     0.050685
NWAmes     0.050000
SawyerW    0.040411
BrkSide    0.039726
Crawfor    0.034932
Mitchel    0.033562
NoRidge    0.028082
Timber     0.026027
IDOTRR     0.025342
ClearCr    0.019178
StoneBr    0.017123
SWISU      0.017123
MeadowV    0.011644
Blmngtn    0.011644
BrDale     0.010959
Veenker    0.007534
NPkVill    0.006164
Blueste    0.001370
Name: Neighborhood, dtype: float64



Frequency table for Condition1 ============
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: Condition1, dtype: int64

Relative frequency table for Condition1 ============
Norm      0.863014
Feedr     0.055479
Artery    0.032877
RRAn      0.017808
PosN      0.013014
RRAe      0.007534
PosA      0.005479
RRNn      0.003425
RRNe      0.001370
Name: Condition1, dtype: float64



Frequency table for Condition2 ============
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: Condition2, dtype: int64

Relative frequency table for Condition2 ============
Norm      0.989726
Feedr     0.004110
Artery    0.001370
RRNn      0.001370
PosN      0.001370
PosA      0.000685
RRAn      0.000685
RRAe      0.000685
Name: Condition2, dtype: float64



Frequency table for BldgType ============
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: BldgType, dtype: int64

Relative frequency table for BldgType ============
1Fam      0.835616
TwnhsE    0.078082
Duplex    0.035616
Twnhs     0.029452
2fmCon    0.021233
Name: BldgType, dtype: float64



Frequency table for HouseStyle ============
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64

Relative frequency table for HouseStyle ============
1Story    0.497260
2Story    0.304795
1.5Fin    0.105479
SLvl      0.044521
SFoyer    0.025342
1.5Unf    0.009589
2.5Unf    0.007534
2.5Fin    0.005479
Name: HouseStyle, dtype: float64



Frequency table for RoofStyle ============
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: RoofStyle, dtype: int64

Relative frequency table for RoofStyle ============
Gable      0.781507
Hip        0.195890
Flat       0.008904
Gambrel    0.007534
Mansard    0.004795
Shed       0.001370
Name: RoofStyle, dtype: float64



Frequency table for RoofMatl ============
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: RoofMatl, dtype: int64

Relative frequency table for RoofMatl ============
CompShg    0.982192
Tar&Grv    0.007534
WdShngl    0.004110
WdShake    0.003425
Metal      0.000685
Membran    0.000685
Roll       0.000685
ClyTile    0.000685
Name: RoofMatl, dtype: float64



Frequency table for Exterior1st ============
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: Exterior1st, dtype: int64

Relative frequency table for Exterior1st ============
VinylSd    0.352740
HdBoard    0.152055
MetalSd    0.150685
Wd Sdng    0.141096
Plywood    0.073973
CemntBd    0.041781
BrkFace    0.034247
WdShing    0.017808
Stucco     0.017123
AsbShng    0.013699
BrkComm    0.001370
Stone      0.001370
AsphShn    0.000685
ImStucc    0.000685
CBlock     0.000685
Name: Exterior1st, dtype: float64



Frequency table for Exterior2nd ============
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: Exterior2nd, dtype: int64

Relative frequency table for Exterior2nd ============
VinylSd    0.345205
MetalSd    0.146575
HdBoard    0.141781
Wd Sdng    0.134932
Plywood    0.097260
CmentBd    0.041096
Wd Shng    0.026027
Stucco     0.017808
BrkFace    0.017123
AsbShng    0.013699
ImStucc    0.006849
Brk Cmn    0.004795
Stone      0.003425
AsphShn    0.002055
Other      0.000685
CBlock     0.000685
Name: Exterior2nd, dtype: float64



Frequency table for MasVnrType ============
None       864
BrkFace    445
Stone      128
BrkCmn      15
Name: MasVnrType, dtype: int64

Relative frequency table for MasVnrType ============
None       0.595041
BrkFace    0.306474
Stone      0.088154
BrkCmn     0.010331
Name: MasVnrType, dtype: float64



Frequency table for ExterQual ============
TA    906
Gd    488
Ex     52
Fa     14
Name: ExterQual, dtype: int64

Relative frequency table for ExterQual ============
TA    0.620548
Gd    0.334247
Ex    0.035616
Fa    0.009589
Name: ExterQual, dtype: float64



Frequency table for ExterCond ============
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: ExterCond, dtype: int64

Relative frequency table for ExterCond ============
TA    0.878082
Gd    0.100000
Fa    0.019178
Ex    0.002055
Po    0.000685
Name: ExterCond, dtype: float64



Frequency table for Foundation ============
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: Foundation, dtype: int64

Relative frequency table for Foundation ============
PConc     0.443151
CBlock    0.434247
BrkTil    0.100000
Slab      0.016438
Stone     0.004110
Wood      0.002055
Name: Foundation, dtype: float64



Frequency table for BsmtQual ============
TA    649
Gd    618
Ex    121
Fa     35
Name: BsmtQual, dtype: int64

Relative frequency table for BsmtQual ============
TA    0.456079
Gd    0.434294
Ex    0.085032
Fa    0.024596
Name: BsmtQual, dtype: float64



Frequency table for BsmtCond ============
TA    1311
Gd      65
Fa      45
Po       2
Name: BsmtCond, dtype: int64

Relative frequency table for BsmtCond ============
TA    0.921293
Gd    0.045678
Fa    0.031623
Po    0.001405
Name: BsmtCond, dtype: float64



Frequency table for BsmtExposure ============
No    953
Av    221
Gd    134
Mn    114
Name: BsmtExposure, dtype: int64

Relative frequency table for BsmtExposure ============
No    0.670183
Av    0.155415
Gd    0.094233
Mn    0.080169
Name: BsmtExposure, dtype: float64



Frequency table for BsmtFinType1 ============
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: BsmtFinType1, dtype: int64

Relative frequency table for BsmtFinType1 ============
Unf    0.302178
GLQ    0.293746
ALQ    0.154603
BLQ    0.104006
Rec    0.093465
LwQ    0.052003
Name: BsmtFinType1, dtype: float64



Frequency table for BsmtFinType2 ============
Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: BsmtFinType2, dtype: int64

Relative frequency table for BsmtFinType2 ============
Unf    0.883263
Rec    0.037975
LwQ    0.032349
BLQ    0.023207
ALQ    0.013361
GLQ    0.009845
Name: BsmtFinType2, dtype: float64



Frequency table for Heating ============
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: Heating, dtype: int64

Relative frequency table for Heating ============
GasA     0.978082
GasW     0.012329
Grav     0.004795
Wall     0.002740
OthW     0.001370
Floor    0.000685
Name: Heating, dtype: float64



Frequency table for HeatingQC ============
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: HeatingQC, dtype: int64

Relative frequency table for HeatingQC ============
Ex    0.507534
TA    0.293151
Gd    0.165068
Fa    0.033562
Po    0.000685
Name: HeatingQC, dtype: float64



Frequency table for Electrical ============
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

Relative frequency table for Electrical ============
SBrkr    0.914325
FuseA    0.064428
FuseF    0.018506
FuseP    0.002056
Mix      0.000685
Name: Electrical, dtype: float64



Frequency table for KitchenQual ============
TA    735
Gd    586
Ex    100
Fa     39
Name: KitchenQual, dtype: int64

Relative frequency table for KitchenQual ============
TA    0.503425
Gd    0.401370
Ex    0.068493
Fa    0.026712
Name: KitchenQual, dtype: float64



Frequency table for Functional ============
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: Functional, dtype: int64

Relative frequency table for Functional ============
Typ     0.931507
Min2    0.023288
Min1    0.021233
Mod     0.010274
Maj1    0.009589
Maj2    0.003425
Sev     0.000685
Name: Functional, dtype: float64



Frequency table for FireplaceQu ============
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: FireplaceQu, dtype: int64

Relative frequency table for FireplaceQu ============
Gd    0.493506
TA    0.406494
Fa    0.042857
Ex    0.031169
Po    0.025974
Name: FireplaceQu, dtype: float64



Frequency table for GarageType ============
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64

Relative frequency table for GarageType ============
Attchd     0.630892
Detchd     0.280638
BuiltIn    0.063814
Basment    0.013778
CarPort    0.006526
2Types     0.004351
Name: GarageType, dtype: float64



Frequency table for GarageFinish ============
Unf    605
RFn    422
Fin    352
Name: GarageFinish, dtype: int64

Relative frequency table for GarageFinish ============
Unf    0.438724
RFn    0.306019
Fin    0.255257
Name: GarageFinish, dtype: float64



Frequency table for GarageQual ============
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: GarageQual, dtype: int64

Relative frequency table for GarageQual ============
TA    0.950689
Fa    0.034808
Gd    0.010152
Ex    0.002175
Po    0.002175
Name: GarageQual, dtype: float64



Frequency table for GarageCond ============
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: GarageCond, dtype: int64

Relative frequency table for GarageCond ============
TA    0.961566
Fa    0.025381
Gd    0.006526
Po    0.005076
Ex    0.001450
Name: GarageCond, dtype: float64



Frequency table for PavedDrive ============
Y    1340
N      90
P      30
Name: PavedDrive, dtype: int64

Relative frequency table for PavedDrive ============
Y    0.917808
N    0.061644
P    0.020548
Name: PavedDrive, dtype: float64



Frequency table for PoolQC ============
Gd    3
Ex    2
Fa    2
Name: PoolQC, dtype: int64

Relative frequency table for PoolQC ============
Gd    0.428571
Ex    0.285714
Fa    0.285714
Name: PoolQC, dtype: float64



Frequency table for Fence ============
MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: Fence, dtype: int64

Relative frequency table for Fence ============
MnPrv    0.558719
GdPrv    0.209964
GdWo     0.192171
MnWw     0.039146
Name: Fence, dtype: float64



Frequency table for MiscFeature ============
Shed    49
Gar2     2
Othr     2
TenC     1
Name: MiscFeature, dtype: int64

Relative frequency table for MiscFeature ============
Shed    0.907407
Gar2    0.037037
Othr    0.037037
TenC    0.018519
Name: MiscFeature, dtype: float64



Frequency table for SaleType ============
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: SaleType, dtype: int64

Relative frequency table for SaleType ============
WD       0.867808
New      0.083562
COD      0.029452
ConLD    0.006164
ConLI    0.003425
ConLw    0.003425
CWD      0.002740
Oth      0.002055
Con      0.001370
Name: SaleType, dtype: float64



Frequency table for SaleCondition ============
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: SaleCondition, dtype: int64

Relative frequency table for SaleCondition ============
Normal     0.820548
Partial    0.085616
Abnorml    0.069178
Family     0.013699
Alloca     0.008219
AdjLand    0.002740
Name: SaleCondition, dtype: float64

#### 7. [15 pts] <a class="anchor" id="bullet7"></a>This question does not use the dataset used in the previous HW questions. Give a function that accepts unlimited arguments, checks and counts how many data types are in those arguments. Finally return the total in a list. This list should count the following object types, in this order:

In [16]:
def count_datatypes(*args):
    # create a dictionary to hold the count of each data type
    counts = {
        "int": 0,
        "str": 0,
        "bool": 0,
        "list": 0,
        "tuple": 0,
        "dict": 0
    }
    
    # loop through each argument
    for arg in args:
        # get the type of the argument
        arg_type = type(arg).__name__
        
        # increment the count for the corresponding data type
        if arg_type == "int":
            counts["int"] += 1
        elif arg_type == "str":
            counts["str"] += 1
        elif arg_type == "bool":
            counts["bool"] += 1
        elif arg_type == "list":
            counts["list"] += 1
        elif arg_type == "tuple":
            counts["tuple"] += 1
        elif arg_type == "dict":
            counts["dict"] += 1
    
    # return the counts as a list:
    return [counts["int"], counts["str"], counts["bool"], counts["list"], counts["tuple"], counts["dict"]]
#try this example:
count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1)

[3, 0, 0, 1, 1, 0]

[int, str, bool, list, tuple, dictionary]  
Several examples are below. Your function should return the list associated with each input.  
count_datatypes(1, 45, "Hi", False) âžž [2, 1, 1, 0, 0, 0]

count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1) âžž [3, 0, 0, 1, 1, 0]

count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1, 3], {"Brayan": 18}, 25, 23) âžž [2, 2, 3, 1, 0, 2]

count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6]) âžž [2, 0, 1, 2, 2, 0]

* [Back to Top ](#bullet8)